
naver:
  client:
    id: vwenkemW8AlO1_A47de4
    secret: kwHkuZbj0h
  url:
    search:
      blog: "https://openapi.naver.com/v1/search/blog.json"
      image: "https://openapi.naver.com/v1/search/image"
      local: "https://openapi.naver.com/v1/search/local.json"
server:
  port: 8091
spring:

  mvc:

    pathmatch:

      matching-strategy: ant_path_matcher